name = "TikhonovFenichelReductions"
uuid = "66629163-d46e-44ca-9a00-7025b1e168e6"
authors = ["jo-ap"]
version = "0.3.4"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[weakdeps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"

[extensions]
CatalystExt = "Catalyst"

[compat]
Catalyst = ">=14"
DocStringExtensions = "0.9"
LaTeXStrings = "1.3"
Latexify = "0.16"
Logging = "1.9"
Oscar = "1.0.0 - 1.2.1, 1.3.1, 1.4"
Pkg = "1.9"
julia = "1.9"
